import { Character } from './types';

export const WORLD_PRESETS: Record<'en' | 'zh', string[]> = {
  en: [
    "Cyberpunk Neo-Tokyo: A neon-drenched metropolis where corporations rule and technology is a drug.",
    "High Fantasy Kingdom: A world of magic, dragons, and ancient prophecies in the land of Eldoria.",
    "Post-Apocalyptic Wasteland: Earth after the Great Collapse, where water is gold and mutants roam.",
    "Victorian Steampunk: An alternate 19th century powered by steam, gears, and sky-pirates.",
    "Cosmic Horror Space Station: A lonely research station orbiting a dying star, where reality is fraying."
  ],
  zh: [
    "赛博朋克新东京：霓虹闪烁的大都市，企业统治一切，技术即是毒品。",
    "高魔奇幻王国：埃尔多利亚大陆，一个充满魔法、巨龙和古老预言的世界。",
    "废土末世：大崩溃后的地球，水比金子还贵，变异生物横行。",
    "维多利亚蒸汽朋克：由蒸汽、齿轮和空贼驱动的平行 19 世纪。",
    "深空恐怖空间站：围绕一颗垂死恒星运行的孤独研究站，现实正在崩塌。"
  ]
};

export const CHAR_PRESETS: Record<'en' | 'zh', Character[]> = {
  en: [
    { name: "Kael", gender: "Male", traits: "Tech-savvy Hacker with a mysterious past." },
    { name: "Lyra", gender: "Female", traits: "Brave Paladin seeking redemption." },
    { name: "Jax", gender: "Other", traits: "Scavenger Survivor who knows the wasteland's secrets." },
    { name: "Professor Pips", gender: "Male", traits: "Eccentric Inventor with a mechanical owl." },
    { name: "Dr. Vane", gender: "Female", traits: "Paranoid Scientist who saw too much in the void." }
  ],
  zh: [
    { name: "凯尔", gender: "Male", traits: "精通技术的黑客，有着神秘的过去。" },
    { name: "莱拉", gender: "Female", traits: "寻求救赎的勇敢圣骑士。" },
    { name: "贾克斯", gender: "Other", traits: "知道废土秘密的拾荒幸存者。" },
    { name: "皮普斯教授", gender: "Male", traits: "带着机械猫头鹰的古怪发明家。" },
    { name: "范恩博士", gender: "Female", traits: "在虚空中见识过太多的偏执科学家。" }
  ]
};

export const UI_STRINGS: Record<'en' | 'zh', any> = {
  en: {
    title: "AI Narrative Weaver",
    selectLang: "Select Interaction Language",
    chooseWorld: "Choose your world view...",
    chooseChapters: "How many chapters to play?",
    chaptersDesc: "Each chapter contains 4 interactions.",
    customWorld: "Or define your own:",
    worldPlaceholder: "Describe your world...",
    whoAreYou: "Who are you in this world?",
    customChar: "Custom Character:",
    name: "Name",
    traits: "Traits",
    create: "Create",
    ready: "The threads of fate are ready to be woven.",
    begin: "Begin Journey",
    world: "World",
    protagonist: "Protagonist",
    initializing: "Initializing Narrative...",
    status: "Status",
    inventory: "Inventory",
    map: "Map",
    rules: "Rules",
    chapters: "Chapters",
    settings: "Settings",
    reset: "Reset Game",
    resetConfirm: "Are you sure you want to reset the game? All progress will be lost.",
    gameOver: "Game Over",
    reweave: "Re-weave Reality",
    laws: "The Laws of this Reality",
    emptyInventory: "Your pockets are empty...",
    weather: "Weather",
    time: "Time",
    scene: "Current Scene",
    visualizing: "Visualizing scene...",
    weaverWorking: "The Weaver is working...",
    explore: "Explore",
    endingHappy: "Happy",
    endingBad: "Bad",
    endingOpen: "Open",
    happyQuote: "You navigated the threads of fate with wisdom.",
    badQuote: "The world claimed you as its own.",
    openQuote: "The story ends, but the echoes remain.",
    vitality: "Vitality",
    environment: "Environment",
    violationDesc: "Breaking world rules leads to bad endings.",
    whatWillYouDo: "What will you do?",
    endingLabel: "Ending",
    guideTitle: "Game Guide",
    guideWorld: "Current World",
    guideChar: "Protagonist",
    guideRules: "Initial Rules",
    guideTime: "Current Time",
    guideWeather: "Current Weather",
    guideStructure: "Game Structure",
    guideChapters: "5 Chapters",
    guideSteps: "4 Interactions per Chapter",
    guideProgression: "Map expands as you progress",
    guideEnding: "Multiple endings based on status/violations",
    guideItems: "Click items in inventory to use them",
    guideWeatherTimeTitle: "Weather & Time System",
    guideWeatherTimeDesc: "Time Multiplier: Morning (x0.8), Afternoon (x1.0), Night (x1.2)\nWeather Multiplier: Good (x0.8), Normal (x1.0), Extreme (x1.2)\nFinal Violation = Base × Time × Weather\n\nExtreme Weather (Ch 2-4):\n🌧 Rain: Muddy paths, slower movement\n🌫 Fog: Unexplored areas hidden (???)\n🌪 Storm: Locations blocked or new dangers",
    summaryTitle: "Journey Summary",
    summaryAccomplishments: "Accomplishments",
    summaryItems: "Items Obtained",
    summaryDifficulties: "Difficulties Faced",
    summaryViolations: "Rule Violations",
    warning: "WARNING: RULE VIOLATED!",
    reviewJourney: "Review Journey",
    generatingVideo: "Generating Video...",
    joiningVideo: "Joining Videos...",
    viewVideo: "View Video",
    scriptTitle: "Complete Script",
    storyboardTitle: "Storyboard"
  },
  zh: {
    title: "AI 叙事编织者",
    selectLang: "选择交互语言",
    chooseWorld: "选择你的世界观...",
    chooseChapters: "你想玩多少章？",
    chaptersDesc: "每一章包含 4 次交互。",
    customWorld: "或者自定义：",
    worldPlaceholder: "描述你的世界...",
    whoAreYou: "在这个世界中，你是谁？",
    customChar: "自定义角色：",
    name: "名字",
    traits: "特质",
    create: "创建",
    ready: "命运之线已准备好被编织。",
    begin: "开始旅程",
    world: "世界",
    protagonist: "主角",
    initializing: "正在初始化叙事...",
    status: "状态",
    inventory: "物品栏",
    map: "地图",
    rules: "规则",
    chapters: "章节",
    settings: "设置",
    reset: "重置游戏",
    resetConfirm: "你确定要重置游戏吗？所有进度都将丢失。",
    gameOver: "游戏结束",
    reweave: "重塑现实",
    laws: "此现实的法则",
    emptyInventory: "你的口袋空空如也...",
    weather: "天气",
    time: "时间",
    scene: "当前场景",
    visualizing: "正在生成场景...",
    weaverWorking: "编织者正在工作中...",
    explore: "探索",
    endingHappy: "圆满",
    endingBad: "悲惨",
    endingOpen: "开放式",
    happyQuote: "你以智慧指引了命运的丝线。",
    badQuote: "世界将你据为己有。",
    openQuote: "故事结束了，但回声仍在荡漾。",
    vitality: "生命力",
    environment: "环境",
    violationDesc: "违反世界规则会导致坏结局。",
    whatWillYouDo: "你将如何行动？",
    endingLabel: "结局",
    guideTitle: "游戏说明",
    guideWorld: "当前世界观",
    guideChar: "主角信息",
    guideRules: "初始规则",
    guideTime: "当前时间",
    guideWeather: "当前天气",
    guideStructure: "游戏结构",
    guideChapters: "共 5 个章节",
    guideSteps: "每章 4 次交互",
    guideProgression: "地图随进度逐步展开",
    guideEnding: "根据状态/违规情况触发多结局",
    guideItems: "在物品栏点击道具即可使用",
    guideWeatherTimeTitle: "天气与时间系统",
    guideWeatherTimeDesc: "时间系数：白天(x1.0), 黄昏(x1.2), 夜晚(x1.5), 深夜(x2.0)\n天气系数：晴天(x1.0), 雨天(x1.1), 暴风(x1.3), 极端(x1.5)\n最终违规扣血 = 8 × 时间系数 × 天气系数\n\n自然侵蚀：\n白天(0), 黄昏(-1), 夜晚(-2), 深夜(-5)\n连续3轮未休息额外 -3\n到达重大时间点(00:00/03:00)额外 -5",
    summaryTitle: "旅程总结",
    summaryAccomplishments: "完成的事迹",
    summaryItems: "获得的道具",
    summaryDifficulties: "遇到的困难",
    summaryViolations: "违反的规则",
    warning: "警告：违反规则！",
    reviewJourney: "回顾旅程",
    generatingVideo: "正在生成视频...",
    joiningVideo: "正在合并视频...",
    viewVideo: "浏览视频",
    scriptTitle: "完整剧本",
    storyboardTitle: "分镜脚本"
  }
};
